Makefile, README.md
- [WIP] Create Makefile
- Update Makefile to make use of venv
=> build with make

.github/workflows/playground.yml, Makefile, README.md
- Add application make target
- Fix .github/workflows/playground.yml
=> application build script

.github/workflows/application.yml, packages/application/package.json, packages/application/src/index.tsx, packages/stlite-kernel/src/kernel.ts
=> build distribute application package

packages/stlite-kernel/src/ConnectionManager.ts
=> Set process.env.PUBLIC_URL to the basePath field in the baseUriParts object

packages/application/config/webpack.config.js, packages/application/src/index.tsx, packages/stlite-kernel/src/worker.ts
Closes #2
Use `global.dataFrameSerialization` option to avoid using PyArrow.
=> DataFrame support

.gitmodules, Makefile, packages/stlite-kernel/src/declarations.d.ts, packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/worker.ts
=> Remove the local build of blinker since its v1.5 is now installable from PyPI

packages/stlite-kernel/src/react-helpers/download-button.ts, packages/stlite-kernel/src/react-helpers/image-list.ts, packages/stlite-kernel/src/react-helpers/index.ts, packages/stlite-kernel/src/react-helpers/media.ts
=> Create media file helpers and use them in streamlit

packages/application/src/index.tsx, packages/playground/src/App.tsx, packages/stlite-kernel/py/e2etests/tests/conftest.py, packages/toy-app/src/App.tsx
=> Upgrade Pyodide to 0.21.0

packages/stlite-kernel/src/declarations.d.ts, packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/types.d.ts, packages/stlite-kernel/src/worker.ts
=> Install external packages

packages/application/src/index.tsx
=> Add requirements option to mount()

Makefile, packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/worker.ts
=> Upgrade Streamlit to 1.12.0

packages/stlite-kernel/src/declarations.d.ts, packages/stlite-kernel/src/worker.ts
=> Update logger to capture multi-line messages correctly

packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/types.d.ts, packages/stlite-kernel/src/worker.ts
=> Define message types

packages/stlite-kernel/src/declarations.d.ts, packages/stlite-kernel/src/worker.ts
Follow the official doc: https://pyodide.org/en/stable/usage/loading-packages.html#micropip
=> Fix worker to call micropip.install from JS

packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/types.d.ts, packages/stlite-kernel/src/worker.ts
=> Install requirements after initialization

packages/stlite-kernel/package.json, packages/stlite-kernel/src/file.test.ts, packages/stlite-kernel/src/file.ts, packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/types.d.ts, packages/stlite-kernel/src/worker.ts, yarn.lock
Resolves #4 (except async/remote resources)
=> Mount multiple files

packages/stlite-kernel/src/declarations.d.ts, packages/stlite-kernel/src/kernel.ts
=> Enable inline option of worker-loader

.github/workflows/mountable.yml, packages/mountable/package.json
=> Set up CI for @stlite/mountable

packages/stlite-kernel/src/worker.ts
Reverts whitphx/stlite#162
Due to #164
=> Revert "Update Pyodide to 0.21.1"

packages/mountable/config/webpack.config.js, packages/mountable/src/index.tsx
=> Output main.css

packages/playground/src/App.css, packages/playground/src/App.tsx, packages/playground/src/EditorModal.tsx, packages/playground/src/sample_app/declarations.d.ts, packages/playground/src/sample_app/index.ts, packages/playground/src/sample_app/pages/page1.py, packages/playground/src/sample_app/streamlit_app.py
The tab control to switch the main script and the requirements has been removed
so both are now handled as files.
=> Multi-file playground

packages/playground/package.json, packages/playground/src/index.tsx, packages/playground/src/serviceWorkerRegistration.ts, yarn.lock
=> Add the notification about PWA cache update on the playground app

packages/stlite-kernel/src/worker.ts
=> Set logs inside loadPyodideAndPackages() on the worker to inspect performance

.github/workflows/gh-pages.yml, .github/workflows/main.yml
https://python-poetry.org/docs/#installation
> The get-poetry.py script described here will be replaced in Poetry 1.2 by install.python-poetry.org.
This change led these errors: https://github.com/whitphx/stlite/runs/8106837675?check_suite_focus=true#step:4:1
=> Update CI script to the latest verion of Poetry installer (1.2.0)

packages/playground/src/App.tsx, packages/playground/src/index.tsx, packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/types.d.ts, packages/stlite-kernel/src/worker.ts
=> Show the boot-up progress on a toast

packages/sharing-common/tsconfig.json
=> Fix the module type of @stlite/sharing-common

.github/workflows/main.yml, packages/sharing-editor/package.json, packages/sharing-editor/src/App.tsx
=> Build and Deploy the sharing/sharing-editor apps

packages/sharing-editor/src/App.tsx
=> Remove a loophole that has been prepared only for the initial set up and can be a vulnerability

.github/workflows/main.yml, packages/sharing-common/src/index.ts, packages/sharing-common/src/messages.ts, packages/sharing-editor/package.json, packages/sharing-editor/src/App.tsx, packages/sharing-editor/src/Editor/BinaryFileEditor.module.css, packages/sharing-editor/src/Editor/BinaryFileEditor.tsx, packages/sharing-editor/src/Editor/Editor.module.css, packages/sharing-editor/src/Editor/FileUploader.tsx, packages/sharing-editor/src/Editor/file.ts, packages/sharing-editor/src/Editor/index.tsx, packages/sharing-editor/src/StliteSharingIFrame.tsx, packages/sharing/package.json, packages/sharing/src/App.tsx
For #104 #68 
About the communication between the editor app and the sharing app and some tips around it such as origin checking,
read: https://javascript.info/cross-window-communication
=> Editor app using monaco for the Sharing service, for creating/updating files

packages/sharing-common/src/messages.ts, packages/sharing-editor/src/App.tsx, packages/sharing-editor/src/Editor/Tab.module.css, packages/sharing-editor/src/Editor/Tab.tsx, packages/sharing-editor/src/Editor/index.tsx, packages/sharing/src/App.tsx, packages/stlite-kernel/src/file.test.ts, packages/stlite-kernel/src/file.ts, packages/stlite-kernel/src/kernel.ts, packages/stlite-kernel/src/types.d.ts, packages/stlite-kernel/src/worker.ts
=> StliteKernel.renameFile() and file renaming on the editor for the sharing app

packages/sharing-editor/src/Editor/Tab.module.css, packages/sharing-editor/src/Editor/Tab.tsx, packages/sharing-editor/src/Editor/index.tsx
=> New file button on the editor

packages/sharing-editor/src/Editor/Tab.module.css, packages/sharing-editor/src/Editor/Tab.tsx
=> File name editor on the tab

packages/sharing-common/src/compress.test.ts, packages/sharing-common/src/compress.ts
=> Fix encodeAppData to deal with the binary data generated from ts-proto

packages/sharing-common/src/messages.ts, packages/sharing-editor/src/App.tsx, packages/sharing/src/App.tsx
=> Set a special file name for requirements and update the editor to trigger installation if that file is written

packages/sharing-editor/src/Editor/components/Tab.tsx, packages/sharing-editor/src/Editor/index.tsx
=> Block file name edit on the entrypoint file

packages/sharing-editor/src/Editor/index.tsx
=> Keep the tab order over file creation, deletion, and rename

packages/sharing-editor/src/App.tsx, packages/sharing-editor/src/Editor/index.tsx
Necessary for #244 to work with #246
=> Move the delete confirmation from App.tsx to Editor/index.tsx as it's necessary for the file name order management to work properly

CHANGELOG.md, packages/stlite-kernel/src/worker.ts
=> Fix worker to patch matplotlib after runtime installs

packages/sharing-editor/src/App.tsx, packages/sharing-editor/src/Editor/Editor.module.scss, packages/sharing-editor/src/Editor/index.tsx
=> Add "requirements" virtual file tab to install the requirements

packages/sharing-common/src/url.test.ts, packages/sharing-common/src/url.ts, packages/sharing/src/App.tsx, packages/stlite-kernel/src/worker.ts
JS version of #266
Resolves #256
=> Update @stlite/sharing to read the source URL from the URL fragment and load it

packages/sharing-editor/src/App.tsx, packages/sharing-editor/src/use-app-data.ts
=> Extract the appData state management into useAppData() hook using a reducer, and set the encoded appData to the editor URL

packages/sharing/package.json, packages/sharing/src/App.tsx, packages/sharing/src/index.tsx
=> Add toasts on the sharing app

packages/stlite-kernel/src/worker.ts
Use an existing library for the same purpose as it's now possible because the worker is compiled via worker-loader that makes it possible for the worker code to act like a normal module and import external packages.
=> Refactoring replacing a self-implementation with the PromiseDelegate class from @lumino/coreutils

packages/sharing/src/App.css, packages/sharing/src/App.tsx, packages/sharing/src/components/InstallErrorToastContent.module.css, packages/sharing/src/components/InstallErrorToastContent.tsx
=> Create <InstallErrorToastContent /> to display the error message on the toast when installing requirements fails

packages/kernel/package.json
=> Set @stlite/kernel public

packages/desktop/package.json, packages/desktop/pyodide-files.txt
=> Extract only necessary Pyodide files into the build dir

README.md, packages/kernel/src/worker.ts
=> Mock st.spinner() that does not work on Pyodide

.gitignore
=> Add vim files to `.gitignore`

packages/kernel/src/requirements.test.ts, packages/kernel/src/requirements.ts, packages/kernel/src/worker.ts
=> Verify the requirement names not to include emfs: and file: schemes

packages/desktop-cli/README.md
Love the desktop app option! Just some simple wording changes to clearer for people unfamiliar with building npm packages (me 😄 ). Feel free to disregard & close.
=> Wording stlite desktop cli instrunctions

packages/sharing-editor/bin/gen-sample-app-manifests-json.ts
=> Exclude the number prefix from the sample app IDs

.github/workflows/gh-pages.yml
=> Remove the steps building and deploying the playground app from the gh-pages CI workflow

packages/desktop/src/App.tsx, packages/kernel/src/kernel.ts, packages/kernel/src/types.d.ts, packages/kernel/src/worker.ts, packages/mountable/src/options.test.ts, packages/mountable/src/options.ts, packages/sharing/src/App.tsx, packages/toy-app/src/App.tsx
=> Remove the command option from the kernel

.github/workflows/main.yml
=> Remove PUBLIC_URL from the build-desktop CI job

packages/kernel/src/worker.ts
=> Fix the logs in kernel/worker.ts for clearer logs and easy profiling

packages/desktop/package.json, packages/desktop/scripts/build_bin.js
Successor to #439
For https://github.com/whitphx/stlite/issues/435
=> Unbundle some packages from dump_artifacts.js

README.md, packages/desktop-cli/README.md, packages/desktop/README.md, packages/sharing-editor/src/components/PreviewToolBar.tsx
=> Move the content from desktop-cli/README.md desktop/README.md

.github/workflows/main.yml
=> Set up the test-sharing-editor step on the CI flow

Makefile, packages/common-react/tsconfig.json, packages/desktop/craco.config.js, packages/kernel/src/kernel.ts, packages/kernel/src/worker.ts, packages/mountable/config/webpack.config.js, packages/sharing/craco.config.js, yarn.lock
=> dev/upgrade streamlit 1.17

packages/sharing-editor/public/samples/011_component_gallery/requirements.txt
=> Add pydeck to packages/sharing-editor/public/samples/011_component_gallery/requirements.txt

packages/kernel/src/mock.ts, packages/kernel/src/worker.ts
=> Mock pyarrow when restoring a snapshot

packages/desktop/README.md
=> Add cross-env to the sample package.json in desktop/README.md

.github/workflows/main.yml
=> Remove unnecessary CI flow deps from build-sharing-editor

packages/kernel/src/streamlit-replacements/lib/ConnectionManager.ts, packages/kernel/src/worker.ts
=> Disable forwardMsg caching

packages/sharing-editor/public/samples/010_streamlit_hello/pages/1_Plotting_Demo.py, packages/sharing-editor/public/samples/010_streamlit_hello/pages/3_DataFrame_Demo.py
Copy them from the upstream repo 1.19.0
=> Fix hello demo pages

.github/workflows/main.yml
=> Add publish-mountable to the deps list of publish-vscode-extension

.github/workflows/main.yml
=> Revert "Replace !failure() to success() in the condition of the publish-vscod…"

Makefile, packages/desktop/bin/dump_artifacts.ts, packages/kernel/src/kernel.ts, packages/kernel/src/streamlit-replacements/lib/ConnectionManager.ts, packages/kernel/src/streamlit-replacements/lib/FileUploadClient.ts, packages/kernel/src/worker.ts, yarn.lock
=> Upgrade Streamlit to 1.21.0

README.md, packages/desktop/src/App.tsx, packages/kernel/src/kernel.ts, packages/kernel/src/types.ts, packages/kernel/src/worker.ts, packages/mountable/src/options.test.ts, packages/mountable/src/options.ts, packages/sharing/src/App.tsx
=> Add an archives option to load and unpack archive files into the virtual file system

Makefile, packages/desktop/bin/dump_artifacts.ts, packages/kernel/py/stlite-server/stlite_server/media_file_handler.py, packages/kernel/py/stlite-server/tests/test_server.py, packages/kernel/src/kernel.ts, packages/kernel/src/streamlit-replacements/lib/ConnectionManager.ts
Update on `kernel/py/stlite-server` is needed to catch up with the changes found with `git diff 1.18.1 1.24.0  --relative=lib/streamlit/web/server`
=> Upgrade Streamlit to 1.24.0

packages/desktop/README.md
=> Update desktop/README.md describing the embed mode config

packages/sharing-editor/src/components/ResponsiveSideBySidePanes.module.scss
=> Fix the side-by-side view style

packages/desktop/bin/dump_artifacts.ts
=> Fix the @stlite/desktop dump script to dump the manifest file with the correct paths

.github/workflows/main.yml, Makefile, packages/common-react/src/toastify-components/callbacks.tsx, packages/mountable/__mocks__/@stlite/common-react.ts, packages/mountable/package.json, packages/mountable/src/index.tsx, packages/mountable/src/options.test.ts, packages/mountable/src/options.ts
=> Add onError option to the mountable package

.github/workflows/main.yml
=> Set generate_release_notes: true for softprops/action-gh-release@v1

packages/kernel/src/worker.ts
=> Fix the error serialization for the inter-thread messaging

packages/sharing-editor/src/App.tsx, packages/sharing-editor/src/router.ts
=> Hide the side menu when `?embed=true` is set

README.md, packages/desktop/README.md, packages/desktop/bin-src/dump_artifacts/index.ts, packages/desktop/electron/main.ts, packages/desktop/electron/preload.ts, packages/desktop/electron/tsconfig.json, packages/desktop/package.json, packages/desktop/src/App.tsx, packages/desktop/src/global.d.ts, packages/kernel/src/declarations.d.ts, packages/kernel/src/kernel.ts, packages/kernel/src/types.ts, packages/kernel/src/worker.ts, packages/mountable/src/options.ts
=> IDBFS for data persistence

packages/sharing-editor/public/samples/011_component_gallery/pages/status.progress.py, packages/sharing-editor/public/samples/011_component_gallery/pages/status.status.py, packages/sharing-editor/public/samples/011_component_gallery/pages/status.status1.py, packages/sharing-editor/public/samples/011_component_gallery/pages/status.toast1.py, packages/sharing-editor/public/samples/011_component_gallery/pages/status.toast2.py, packages/sharing-editor/public/samples/020_custom_components/pages/lottie.py
=> Replace time.sleep with asyncio.sleep in the component gallery sample

packages/common-react/src/toastify-components/stlite-kernel-with-toast.tsx, packages/desktop/electron/worker.ts, packages/kernel/src/auto-install.ts, packages/kernel/src/kernel.ts, packages/kernel/src/module-auto-load.ts, packages/kernel/src/types.ts, packages/kernel/src/worker-runtime.ts, packages/kernel/src/worker.ts, packages/sharing-common/src/messages.ts, packages/sharing-editor/src/App.tsx, packages/sharing-editor/src/Editor/components/Tab.module.scss, packages/sharing-editor/src/Editor/index.tsx, packages/sharing-editor/src/StliteSharingIFrame/index.tsx, packages/sharing/src/App.tsx
Resolves #857
But `pyodide.loadPackagesFromImports()` only loads prebuilt packages. Should it be deployed?
> https://pyodide.org/en/stable/usage/loading-packages.html
=> Auto-install the imported packages

packages/desktop/electron/main.ts, packages/desktop/src/nodejs-worker.ts, packages/kernel/src/pyodide-loader.test.ts, packages/kernel/src/pyodide-loader.ts, packages/kernel/src/worker-runtime.ts
=> Add file:// schema to the Pyodide ESM path in the desktop package

packages/sharing-editor/public/samples/011_component_gallery/pages/data.column_config.py, packages/sharing-editor/public/samples/011_component_gallery/pages/data.link_column.py, packages/sharing-editor/public/samples/011_component_gallery/pages/data.text_column.py
https://github.com/streamlit/docs/pull/1087
=> Fix 011_component_gallery/pages/*.py to use raw string to write regex

packages/desktop/electron/ipc-utils.test.ts, packages/desktop/electron/ipc-utils.ts, packages/desktop/electron/main.ts
=> Fix isValidIpcSender to compare the URLs by .startsWith() instead of ===

README.md, packages/desktop/README.md
=> Update README.md and desktop/README.md

README.md, packages/desktop/README.md
=> Rename 'stlite' to the capitalized 'Stlite' and update the subtitle

packages/kernel/src/mock.ts, packages/kernel/src/worker-runtime.ts
=> Mock toml with impl using tomllib

packages/desktop/samples/basic/.streamlit/config.toml, packages/desktop/samples/basic/package.json
=> Add .streamlit/config.toml to the basic sample of the desktop app

packages/kernel/src/cross-origin-worker.ts
=> Fix CrossOriginWorker to work in FireFox

packages/common-react/src/toastify-components/stlite-kernel-with-toast.tsx, packages/kernel/src/kernel.ts, packages/kernel/src/types.ts, packages/kernel/src/worker-runtime.ts, packages/mountable/src/index.tsx
=> Add .readFile()

packages/desktop/README.md, packages/desktop/electron/main.ts, packages/desktop/electron/manifest.spec.ts, packages/desktop/electron/manifest.ts
=> NODEFS path placeholders resolved with Electron's app.getPath()

packages/kernel/py/stlite-lib/stlite_lib/codemod.py, packages/kernel/py/stlite-lib/stlite_lib_tests/codemod_test.py
=> Convert `asyncio.run(fn())` to `await fn()`

packages/kernel/src/cross-origin-worker.ts
=> Update CrossOriginWorker to work with type=module

packages/common-react/package.json, packages/common-react/src/toastify-components/ErrorToastContent.tsx, packages/common-react/src/toastify-components/callbacks.tsx, packages/common-react/src/toastify-components/stlite-kernel-with-toast.tsx, packages/common-react/src/toastify-components/toastify.css, packages/desktop/package.json, packages/desktop/src/App.tsx, packages/desktop/src/index.tsx, packages/mountable/package.json, packages/mountable/src/mount.tsx, packages/sharing/package.json, packages/sharing/src/App.tsx, packages/sharing/src/index.tsx, yarn.lock
=> Update react-toastify to v11

packages/sharing-editor/src/export/html.spec.ts, packages/sharing-editor/src/export/html.ts
Merge this after releasing the new version of `@stlite/mountable`.
=> Update the HTML exporter for the new API

.github/workflows/main.yml
=> Migrate from cloudflare/pages-action to cloudflare/wrangler-action

.github/workflows/main.yml, packages/desktop/bin-src/dump_artifacts/pyodide_packages.test.ts, packages/desktop/bin-src/dump_artifacts/pyodide_packages.ts
=> Fix a bug of `dump` command in `@stlite/desktop`

.github/workflows/main.yml, .github/workflows/post-build.yml
=> Move the jobs that follow the build jobs to a separate workflow

packages/browser/package.json, packages/browser/src/mount.tsx, packages/browser/src/options.ts, packages/browser/vite.config.ts, yarn.lock
=> Make `@stlite/browser` npm-installable with type declaration files

README.md
=> Update README.md about version resolution failures

packages/kernel/src/cross-origin-worker.ts, packages/kernel/src/kernel.ts
=> Handle the case where SharedWorker is not available

.github/workflows/test-build.yml, packages/browser/e2e-tests/.gitignore, packages/browser/e2e-tests/browserstack.yml, packages/browser/e2e-tests/package.json, packages/browser/e2e-tests/yarn.lock
=> Set up Browserstack to run the E2E tests on Chrome for Android

.github/workflows/postbuild.yml
=> Fix .github/workflows/postbuild.yml

packages/desktop/package.json, packages/desktop/samples/basic/package.json, packages/desktop/samples/file-persistence-idbfs/package.json, packages/desktop/samples/file-persistence-nodefs/package.json, yarn.lock
Reverts whitphx/stlite#1486
Electron 36 has a regression: https://github.com/electron/electron/issues/47374
=> Revert "Bump electron from 34.3.0 to 36.4.0"

CHANGELOG.md, README.md, packages/browser/.prettierignore, packages/browser/e2e-tests/pages/env-test.html, packages/browser/e2e-tests/pages/test-app-custom-element.html, packages/browser/e2e-tests/pages/test-app.html, packages/browser/e2e-tests/test-utils.ts, packages/browser/e2e-tests/tests/basic.test.ts, packages/browser/e2e-tests/tests/custom-element.test.ts, packages/browser/e2e-tests/tests/env.test.ts, packages/sharing-editor/src/export/html.spec.ts, packages/sharing-editor/src/export/html.ts
=> Update the browser E2E tests to detect 404 links

.github/workflows/postbuild.yml, .github/workflows/test-build.yml
=> Add provenance

packages/kernel/src/code_completion.ts, packages/kernel/src/types.ts, packages/sharing-common/src/messages.ts, packages/sharing-editor/src/Editor/LanguageProviders/CodeCompletionProvider.test.ts, packages/sharing-editor/src/Editor/LanguageProviders/CodeCompletionProvider.ts
=> Add CodeCompletion.complete
