- Makefile
- packages/stlite-kernel/py/stlite-tornado/tornado/httpserver.py
- packages/stlite-kernel/py/stlite-tornado/tornado/httputil.py
- packages/stlite-kernel/py/stlite-tornado/tornado/websocket.py
- packages/stlite-kernel/src/ConnectionManager.ts
- packages/stlite-kernel/src/kernel.ts
- yarn.lock
- Rebase streamlit to 1.10.0
- Update the Streamlit wheel file name to be v1.9.2 (the Git tag is 1.10.0)
- Implement ConnectionManager.getBaseUriParts() with a dummy value for v1.10.0 compatibility
- Implement WebSocketHandler.request.headers for header checkings in server.py in 1.10.0
> Upgrade Streamlit to 1.10.0 tag"

- packages/stlite-kernel/src/ConnectionManager.ts
> Set window.location.pathname to the basePath field in the baseUriParts object

- .github/workflows/gh-pages.yml
https://github.community/t/reuse-jobs-in-a-workflow-with-parameters/215584/2 says
> In principle you have three options to reuse workflow code:
> 
> * Write one job with a [matrix strategy](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix), putting the parameters into the matrix. This keeps all code in one workflow file.
> * Create a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) and call it with the appropriate parameters for each environment.
> * Create a [reusable workflow](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) and call it with the appropriate parameters for each environment.
and this PR took the first option, using a matrix …
> Make the build job on CI parallel

- README.md
- packages/mountable/package.json
- packages/mountable/src/App.test.tsx
- packages/mountable/src/index.tsx
- packages/mountable/src/options.test.ts
- packages/mountable/src/options.ts
- packages/mountable/src/setupTests.ts
- packages/playground/src/App.tsx
- packages/stlite-kernel/src/kernel.ts
- packages/stlite-kernel/src/types.d.ts
- packages/stlite-kernel/src/worker.ts
- packages/toy-app/src/App.tsx
- Create StliteKernel.writeFile and fix the playground app to use it
- Remove mainScriptPath and mainScriptData options from stlite-kernel
- Fix @stlite/mountable and @stlite/playground to use the new API of stlite-kernel
> Create writeFile() and replace mainScriptData with it

- .github/workflows/gh-pages.yml
- packages/mountable/src/index.tsx
- packages/mountable/src/types.d.ts
- packages/mountable/src/url.test.ts
- packages/mountable/src/url.ts
- packages/stlite-kernel/src/kernel.ts
- packages/stlite-kernel/src/url.test.ts
- packages/stlite-kernel/src/url.ts
Until now, if the `stlite.js` is transpiled without a proper `PUBLIC_URL` setting or it is hosted at the URL different from `PUBLIC_URL`, the execution have failed because it could not load the wheel files for the stlite kernel and the JS chunks for the React app as the resolved URLs of these resources were pointing to the wrong locations.
With this change, those URLs will be resolved based on the parent URL of the `stlite.js`, assuming that the `stlite.js` is located at the root directory of the build artifact and the URLs of the wheels and the JS chunks represent the relative paths to the URL of the root directory.
This trick is necessary, for example, to host this package from CDN which assigns URLs to the package that are not controllable from our side and not stable.
> Update to resolve paths when the script is loaded from non-root paths

- packages/mountable/config/webpack.config.js
Because the former one is less descriptive especially when, for example, used without being loaded from a CDN, where the string "stlite" is not included in the resource URL at all.
> Rename main.css to stlite.css

- packages/stlite-kernel/src/streamlit-replacements/lib/ConnectionManager.ts
> Update the `basePath` management so that the URL is updated correctly over the page transitions on MPA

- packages/stlite-kernel/src/worker.ts
~~For #121~~
With the performance inspection in #121, we found this does not affect so much for the performance.
This can be beneficial in that it suppress some warnings that are unavoidable on stlite environment due to network connectivity and it also avoids unnecessary prints which are done with `_print_url()` in the original function.
> Fix the bootstrap Python code to call the customized run() instead of the original bootstrap.run()

- packages/stlite-kernel/src/worker.ts
> Fix the customized run() introduced in #181 that is necessary for matplotlib

- packages/sharing-common/package.json
- packages/sharing-common/src/buffer.test.ts
- packages/sharing-common/src/buffer.ts
- packages/sharing-common/src/compress.ts
- packages/sharing-common/vitest.config.ts
- yarn.lock
Resolves #254
For the current default project including  `logo192.png`,
* The current encoding:
* 7706 bytes
* `Uint8ArrayToString` + `window.btoa` is better than the current implementation in the combination with `LZString.compressToEncodedURIComponent`
* 6544 bytes
```ts
function uint8ArrayToString(buf: Uint8Array): string {
let result = "";
for (let i = 0; i < buf.length; i++) {
result += String.fromCharCode(buf[i]);
}
return result;
}
export function encodeAppData(appData: AppData): string {
const encodedProto = AppData.encode(appData).finish();
const str = uint8ArrayToString(Uint8Array.from(encodedProto));
const base64 = window.btoa(str);
return LZString.compressToEncodedURIComponent(base64)
}
```
* Moreover, Base64 and `LZString.compressToEncodedURIComponent` use [the character …
> Change the URL hash encoding method simply using base64 (base64url) and remove LZString for efficiency

- packages/sharing/src/App.tsx
- packages/stlite-kernel/src/kernel.ts
- packages/stlite-kernel/src/types.d.ts
- packages/stlite-kernel/src/worker.ts
> Add onError to handle errors in the init process and display the error with a toast on @stlite/sharing

- Makefile
As `$(streamlit_wheel)` has been added to the deps of `$(kernel)` at https://github.com/whitphx/stlite/pull/302, it is no longer necessary to be included in the deps of these rules.
> Remove unnecessary deps from some make rules

- packages/sharing-editor/bin/gen-sample-app-manifests-json.ts
- packages/sharing-editor/src/sample-app.ts
> Add the .basePath field on SampleAppManifest model to preserve the directory name

- .github/workflows/gh-pages.yml
- .github/workflows/main.yml
Resolves #411
We give up making the Python version in the CI workflows sync to the Python version on the Pyodide runtime at the patch version level.
> Remove the Python patch version specification in the CI workflows because the strict version combinations of Python and OS sometimes break

- CHANGELOG.md
- packages/desktop/bin/dump_artifacts.ts
> Fix desktop/bin/dump_artifacts.ts to overwrite the destination build directory by default and introduce the -k option to skip it

- .github/workflows/main.yml
- packages/desktop/electron/__tests__/file.test.ts
- packages/desktop/electron/file.ts
> Fix the initial file setup for @stlite/desktop on Windows

- packages/desktop-cli/package.json
- packages/desktop/package.json
- packages/desktop/pyodide-files.txt
- packages/kernel/package.json
- packages/kernel/src/worker.ts
- yarn.lock
> Upgrade Pyodide to 0.22.1

- packages/kernel/src/worker.ts
Rel: #492 .
This fix should have been introduced in #492 but not.
> Fix modifying matplotlib backend after installing it adapting to the new stlite-server package

- README.md
- packages/sharing-editor/public/samples/011_component_gallery/pages/charts.audio.py
> Update the Streamlit submodule to support top-level await

- README.md
- packages/kernel/src/worker.ts
The idea introduced at https://github.com/whitphx/stlite/issues/64#issuecomment-1274084568 has been correct, and we can now test it with `asyncio.sleep()` because top-level await has been supported since (#514 ).
Then we implement the idea in the actual code to support `st.spinner`.
> Support st.spinner using asyncio instead of threading

- packages/kernel/src/kernel.ts
- packages/kernel/src/streamlit-replacements/lib/ConnectionManager.ts
- packages/kernel/tsconfig.json
- packages/mountable/src/options.ts
- packages/vscode-stlite/src/web/extension.ts
> Override the page link base URL on VSCode WebViews to prevent the page links from opening unnecessary browser tabs

- packages/desktop/electron/main.ts
> Remove handler on the Electron app when the window is closed

- packages/sharing-common/src/consts.ts
- packages/sharing-common/src/url.ts
Accept the `#code=...` syntax in the URL hash with URL-encoded Python code.
> Update stlite sharing to accept the code param in the URL hash

- packages/mountable/src/index.tsx
> Create disableToast and enableToast

- packages/desktop/bin/dump_artifacts.ts
- packages/kernel/src/worker.ts
> Install the user-specified requirements before installing the Streamlit package so users can specify Streamlit's dependencies' versions

- DEVELOPMENT.md
Closes https://github.com/whitphx/stlite/issues/661
> Update DEVELOPMENT.md to include USE_CONSTRAINT_FILE=false

- packages/desktop/bin/dump_artifacts.ts
- packages/kernel/src/worker.ts
> fix/altair ver lt 5.2.0

- Makefile
- packages/common-react/package.json
- packages/desktop/bin/dump_artifacts.ts
- packages/desktop/package.json
- packages/kernel/package.json
- packages/kernel/py/stlite-server/tests/bootstrap_test.py
- packages/kernel/src/kernel.ts
- packages/kernel/src/streamlit-replacements/lib/ConnectionManager.ts
- packages/mountable/package.json
- packages/mountable/src/options.ts
- packages/sharing/package.json
- packages/vscode-stlite/src/web/extension.ts
- yarn.lock
- Upgrade Streamlit to 1.30.0
- Fix hostConfigResponse in Kernel
- Update hostConfigResponse callers
> dev/upgrade streamlit to 1.30.0

- packages/desktop/bin/dump_artifacts.ts
- packages/desktop/package.json
- packages/desktop/pyodide-files.txt
- packages/kernel/package.json
- packages/kernel/src/worker.ts
- yarn.lock
For newer versions of Streamlit (approx. >=1.27.0?), this Pyodide version is necessary for the Pillow's version match.
> Upgrade Pyodide to 0.24.1

- packages/desktop/.gitignore
- packages/desktop/bin/dump_artifacts.ts
- packages/desktop/package.json
- packages/desktop/scripts/build_bin.js
- packages/desktop/scripts/copy_wheels.js
Prepare for #687.
After this change is published, `@stlite/kernel` can stop being published.
> Ship the stlite wheel files with the desktop package

- packages/kernel/py/stlite-server/stlite_server/bootstrap.py
- packages/sharing-editor/public/samples/010_streamlit_hello/pages/2_Mapping_Demo.py
> Restore the pyodide-http patch

- packages/desktop/bin/dump_artifacts.ts
`pyodide.loadPackage()` doesn't throw an error even if it fails to load the package.
It just puts logs as https://github.com/pyodide/pyodide/blob/163a46e3ca5128a5c25b79bb6b4db76b7f5d9b30/src/js/load-package.ts#L529-L536
This PR makes the `dump_artifacts` script to crash at such an error properly.
Rel: https://github.com/whitphx/stlite/issues/648#issuecomment-1997417335
> Update bin/dump_artifacts to catch errors at loadPackage()

- packages/desktop/src/nodejs-worker.ts
- packages/desktop/tsconfig.json
- packages/mountable/tsconfig.json
- packages/sharing/tsconfig.json
> Set `moduleResolution` as `Node` because it's necessary to run correct type checking at build time

- README.md
The current readme still uses a quite old version in the example. This PR updates this to the latest version.
> Update stlite version in Readme

- packages/desktop/package.json
- packages/mountable/package.json
- packages/sharing/package.json
because these packages don't depend on `parquet-wasm` while `@streamlit/lib` does and it's the only package that must have the dependency to `parquet-wasm`.
> Remove parquet-wasm deps from packages/*/package.json

- packages/desktop/README.md
- packages/desktop/bin-src/dump_artifacts/index.ts
- packages/desktop/bin-src/dump_artifacts/pyodide_packages.ts
- packages/desktop/bin-src/dump_artifacts/url.ts
> Add --pyodide-source option and remove manual downloading of the prebuilt packages relying on Pyodide's caching mechanism

- packages/kernel/src/worker-runtime.test.ts
> Fix the Parquet serializer's auto-fixing of non-string column names

- packages/kernel/src/worker-runtime.test.ts
Also looks like the concurrent execution haven't made the test runs faster anyway.
> Disable test.concurrent()

- packages/desktop/src/App.tsx
- packages/kernel/src/kernel.ts
- packages/kernel/src/types.ts
- packages/kernel/src/worker-runtime.ts
The `archives` option was introduced in #567 after `mountedSitePackagesSnapshotFilePath` in #295 so now we can replace `mountedSitePackagesSnapshotFilePath` with `archives` for the same purpose for the simplicity sake.
> Remove the mountedSitePackagesSnapshotFilePath option and use the archive option instead

- packages/kernel/src/worker-runtime.ts
Resolves #1118
Maybe the event loop implementation of Chrome is different from Safari and this bug couldn't happen in Chrome?
> Fix the worker to await httpServer.start() that returns a promise

- .github/actions/init-all/action.yml
- .github/actions/init-node/action.yml
- .github/workflows/main.yml
- Makefile
`actions/setup-node` with `cache: yarn` caches Yarn's global cache instead of the installed packages in the local working directory, e.g. `node_modules` [as described](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data).
Ref: https://stackoverflow.com/questions/70201071/setup-node-restoring-cache-but-still-takes-a-while-to-yarn
Looks like it's a standard way, however, running `yarn install` takes about 40~50secs even with the global cache, so caching `node_modules` can also be an option if it introduces a drastic improvement.
Refs:
* https://tech.dentsusoken.com/entry/2024/03/25/GitHub_Actions_%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC%E8%A8%AD%E8%A8%88%E3%81%AETips_%EF%BD%9E%E3%82%B9%E3%83%A0%E3%83%BC%E3%82%BA%E3%81%AA%E4%BE%9D%E5%AD%9 …
> Cache node_modules

- .github/actions/init-all/action.yml
- .github/workflows/gh-pages.yml
The latest version of uv has an issue when creating venv as https://github.com/astral-sh/uv/issues/10487 and the CI has started to fail due to it.
> Set uv version in the CI workflows as !=0.5.17

- packages/browser/src/mount.tsx
- packages/kernel/src/kernel.ts
> Use classic workers in production for the cross origin worker trick on a page loaded via file:// scheme

- package.json
- yarn.lock
https://x.com/vitest_dev/status/1886691304039489773
> Update vitest to 2.1.9 as Streamlit uses vitest@2 and this patch version is important for security

- packages/browser/src/options.ts
- packages/kernel/src/kernel.ts
- packages/kernel/src/types.ts
- packages/kernel/src/worker-runtime.ts
At Cognite, we have a fork of `stlite` because we need to pass in an authentication token into an environment variable in Python. One way to get rid of this fork is to add the functionality in this PR:
1) a new optional field in `mount` function called `env`: A Record<string,string> object with environment variables to set on initialization.
2) a new kernel function `setEnv` that allows JavaScript to set environment variables at any time later.
It would be super for us to have these features merged into `stlite` and likely useful for other people as well for the same reasons.
> Add env option to mount and setEnv function to kernel

- .github/workflows/main.yml
For external contributors to make their PRs successfully run even without the permission to run the inform-package-stats step.
Rel #1329
> Set continue-on-error to all inform-package-stats steps

- packages/kernel/src/kernel.ts
- packages/kernel/src/language-server/code_completion.ts
- packages/kernel/src/language-server/language-server-loader.ts
- packages/kernel/src/types.ts
- packages/kernel/src/worker-runtime.test.ts
- packages/kernel/src/worker-runtime.ts
At Cognite, we've been using a fork of this repo to inject authentication token, configure startup settings, and implement a language server on top of the existing kernel.
We're hoping to move away from our fork and contribute our language server logic to the upstream repo.
This PR includes the very initial setup for the language server to work and keep the PR size small. I made the following changes:
* It installs `jedi` as a library when loading the kernel and added InMessage and ReplyMessage types
* Added a method in the Kernel for getting the code_completions
* Added a listener in the worker to listen and execute the python code that generates the suggestions
* I modified the worker-runtime test to test the code completion part. I did the changes there because the initialization code …
> feat: add language server support in the kernel

- packages/kernel/src/kernel.ts
- packages/sharing-common/src/messages.ts
- packages/sharing-common/src/proto/models.proto
- packages/sharing-common/src/url.spec.ts
- packages/sharing-editor/src/StliteSharingIFrame/index.tsx
- packages/sharing/src/App.tsx
- packages/sharing/src/urlparams.ts
Updating the code in the sharing app to:
- Decode the URL and pass the languageServer option to the Kernel
- Listen for messages returned from the worker for code_complete and forward the data to sharing-editor
1. Build `kernel` and `sharing-common`
2. Start sharing app - `EDITOR_APP_ORIGIN="http://localhost:5173" yarn start`
3. Open an app with the sharing URL that inclides the languageServer field. You can use [this one](http://localhost:3000/#!ChBzdHJlYW1saXRfYXBwLnB5EkcKEHN0cmVhbWxpdF9hcHAucHkSMwoxaW1wb3J0IHN0cmVhbWxpdCBhcyBzdAoKc3QudGl0bGUoIkhlbGxvIFdvcmxkISIpCiAB) as an example
4. If everything is ok, you will see a toast message being displayed saying "Importing Language Server"
If you want to test the autocomplete, run the `sharing-editor` app and open the browser console and …
> feat: language server setup in the sharing application

- .github/workflows/main.yml
- packages/sharing/package.json
* `EDITOR_APP_ORIGIN_REGEX`: because we started using `pages-deployment-alias-url` rather than `deployment-url` since #1346, the regex had been invalid.
* `EDITOR_APP_ORIGIN` value for local dev had bee invalid since we switched to Vite.
> Fix EDITOR_APP_ORIGIN_REGEX and EDITOR_APP_ORIGIN settings

- packages/browser/src/mount.tsx
To fix a bug introduced in #1388
> Fix `@stlite/browser` to set the good default values to `workerType` and `wheelUrls`

- packages/browser/package.json
Fixes the following warning.
```
▲ [WARNING] The condition "types" here will never be used as it comes after "default" [package.json]
package.json:28:8:
28 │         "types": "./build/stlite.d.ts"
╵         ~~~~~~~
The "default" condition comes earlier and will always be chosen:
package.json:27:8:
27 │         "default": "./build/stlite.js",
╵         ~~~~~~~~~
```
> Fix the order of exports fields in @stlite/browser
